<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="css/reset.css">
	<link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="css/animation.css">
	<link rel="stylesheet" href="css/style.css">
	<title>Portfolio</title>
	
</head>
<body>
	<!--hr-->
	<header>
		<nav id="topNav">
			<ul>
				<li><a href="#home">Accueil</a></li>
				<li><a href="#services">Services</a></li>
				<li><a href="#skills">Compétences</a></li>
				<li><a href="#projects">Projets</a></li>
				<li><a href="#about">A propos</a></li>
				<li><a href="#contact">Contact</a></li>
			</ul>
		</nav>
		<div id="socialNetworks">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
		</div>
	</header>
	<main>
		<nav id="sideNav">
			<ul>
				<li><a class="active" href="#home">Accueil <div class="pastilles"></div></a></li>
				<li><a href="#services">Services <div class="pastilles"></div></a></li>
				<li><a href="#skills">Compétences <div class="pastilles"></div></a></li>
				<li><a href="#projects">Projets <div class="pastilles"></div></a></li>
				<li><a href="#about">A propos <div class="pastilles"></div></a></li>
				<li><a href="#contact">Contact <div class="pastilles"></div></a></li>
			</ul>
		</nav>

		<div id="home">
			<div class="parallax"></div>
			<div id="title">
			    <section>
				    <h1>Xavier Michy</h1>
				    <h2>Développeur/Intégrateur web</h2>
			    </section>
			</div>    
	    </div>				
		<div id="services">
			<div class="wrapper">
			    <h2>Services</h2>
			    <p>Le développement d'un site web est la pierre angulaire de votre stratégie de communication. Les services que je propose sont étudiés pour répondre au mieux à vos attentes.<!--Volé sur wax my web--></p>
			</div>
			<div class="wrapper">
				<section>
					<div>
						<i class="fa fa-desktop"></i>
						<svg width="128px" height="128px">
							<circle cx="50%" cy="50%" r="49%"></circle></svg>
					</div>
					<h4>Site vitrine</h4>
					<p>Développement d'un vitrine digital pour votre activitée.</p>
				</section>
				<section>
					<div>
						<i class="fa fa-shopping-cart"></i>
						<svg width="128px" height="128px">
							<circle cx="50%" cy="50%" r="49%"></circle></svg>
					</div>
					<h4>E-Commerce</h4>
					<p>Un commerce? Une marque? Vendez sur inernet.</p>
				</section>
				<section>
					<div>
						<i class="fa fa-mobile"></i>
						<svg width="128px" height="128px">
							<circle cx="50%" cy="50%" r="49%"></circle></svg>
					</div>
					<h4>Responsive</h4>
					<p>Votre communication est-elle adaptée aux enjeux mobiles?</p>
				</section>
			</div>
		</div>

		<div class="banner">
			<p>Mes compétences aux service de votre projet</p>
		</div>

		<div id="skills">
			<h2>Compétences</h2>
			<section class="wrapper">
				<figure>
					<img src="img/skills/html5.png" alt="Html 5">
					<figcaption>Html 5</figcaption>
				</figure>
				<figure>
					<img src="img/skills/css3.png" alt="CSS 3">
					<figcaption>CSS 3</figcaption>
				</figure>	
				<figure>	
					<img src="img/skills/js.png" alt="Javascript">
					<figcaption>Javascript</figcaption>
				</figure>	
				<figure>	
					<img src="img/skills/jquery.png" alt="JQuery">
					<figcaption>JQuery</figcaption>
				</figure>	
				<figure>	
					<img src="img/skills/php.jpg" alt="Php">
					<figcaption>Php</figcaption>
				</figure>	
				<figure>	
					<img src="img/skills/mysql.png" alt="MySql">
					<figcaption>MySql</figcaption>
				</figure>	
				<figure>	
					<img src="img/skills/bootstrap.png" alt="Bootstrap">
					<figcaption>Bootstrap</figcaption>
				</figure>	
				<figure>	
					<img src="img/skills/responsive.png" alt="Responsive">
					<figcaption>Responsive</figcaption>
				</figure>	
			</section>
		</div>

		<div class="banner">
			<p>Mes compétences aux service de votre projet</p>
		</div>

		<div id="projects">
			<h2>Sélections de réalisations</h2>
			<div class="wrapper">
				<figure>
					<h4>So_Shoot Photography</h4>
					<img src="img/realisations/real1.jpg" alt="Site">
					<figcaption>Site réalisé pour un photographe semi-professionnel. Développé à partir d'un CMS afin de rendre simple et intuitive l'administration du site. </figcaption>
				</figure>
				<figure>
					<h4>So_Shoot Photography</h4>
					<img src="img/realisations/real2.jpg" alt="Site">
					<figcaption>Site réalisé pour un photographe semi-professionnel. Développé à partir d'un CMS afin de rendre simple et intuitive l'administration du site. </figcaption>
				</figure>
				<figure>
					<h4>So_Shoot Photography</h4>
					<img src="img/realisations/real3.jpg" alt="Site">
					<figcaption>Site réalisé pour un photographe semi-professionnel. Développé à partir d'un CMS afin de rendre simple et intuitive l'administration du site. </figcaption>
				</figure>	
			</div>
		</div>

		<div id="about">
			<h2>A propos de moi</h2>
			<div class="wrapper">
				<img src="img/profile/moi.jpg">
				<p>lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet</p>
			</div>
		</div>
		<div id="contact">
			<p>Laissez moi un mail pour parler de votre projet</p>
			<div class="wrapper">
				<form action="#" method="POST">
					<div class="field">
						<label for="name" class="field-label" >Votre nom</label>
						<input type="text" id="name" class="field-input" name="name">
					</div>
					<div class="field">
						<label for="email" class="field-label">Votre email</label>
						<input type="text" id="email" class="field-input" name="email">
					</div>
					<div class="field textarea">
						<label for="message" class="field-label">Votre message</label>
						<textarea class="field-input" id="message" name="message" rows="10" cols="50"></textarea>
					</div>
					<div class="submit">
						<span id="border-top"></span>
						<span id="border-right"></span>
						<span id="border-bottom"></span>
						<span id="border-left"></span>
						<input type="submit" id="submit-contact-form" name="submit" value="Envoyer">
					</div>
				</form>
			</div>	
		</div>
	</main>
	<footer>
		<div></div>

	</footer>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script type="text/javascript" src="js/sideNav.js"></script>
	<script type="text/javascript" src="js/parallax.js"></script>
	<script type="text/javascript" src="js/form.js"></script>
</body>
</html>